### ISSUE TITLE
I play on peaceful or easy

### ISSUE THREAD

**Issue by JohnPone** [BedrockLegends/Monumental-Experience#10]
How do I unlock the difficulty setting after I make a world? I love my natural regen and not having to eat when my character plays.

**Comment by JohnPone** [comment]
Oookaay? This issue got closed...but I never got a response other than to say that my question was closed. Is it a config option and if so which/where is it?

**Comment by BedrockLegends** [comment]
Default options, Just know I am leaving the new version of the pack on 1.16.3 and above to hard.

#The default difficulty selected for newly created worlds.
#Allowed Values: PEACEFUL, EASY, NORMAL, HARD
defaultDifficulty = "HARD"
#Set to true if the difficulty for new world's should be locked ot the specific default. This cannot be unlocked by players without external tools! Probably a bad idea. I don't recommend. Why am I adding this option?
lockDifficulty = true
