### ISSUE TITLE
Request - Crafting Table Recipe - 2.0.beta

### ISSUE THREAD

**Issue by Tylerun** [BedrockLegends/Monumental-Experience#11]
Crafting Table recipe is not possible to make without building the house. House is not needed after building and just takes up space for no reason. 
 
Steps to reproduce
1. Start Fresh
2. JEI Crafting Table
3. Find there is no possible recipe
 
Version: 2.0.beta
Server Version: Beta Hosted by Yall

Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.
No

**Comment by Warbringer12** [comment]
shush
