### ISSUE TITLE
Botania's Rune of Water Uncraftable

### ISSUE THREAD

**Issue by Hamderber** [BedrockLegends/Monumental-Experience#115]
**Issue description:**

Trying to craft a Botania **Rune of Water** simply doesn't work. The recipe is there, but having all the items on the **Runic Altar** doesn't register it as something that can be crafted.

**Modpack Version:**

13.2.4

**Comment by BedrockLegends** [comment]
Looking at the Recipe, This recipe is a default recipe from Botania and not a custom one we made
