### ISSUE TITLE
Circuit Backplane uncraftable

### ISSUE THREAD

**Issue by SzerencsesDenes** [BedrockLegends/Monumental-Experience#116]
**Please do not posted issues that are asking for Server Files**

**Issue description:**
Crafting a Circuit Backplane from immersive engineering needs a Printed Circuit Board from PneumaticCraft, which needs an Unassembled PCB, which needs an Empty PCB which then needs a Circuit Backplane.
 
And there we have a nice and never ending circle which makes this uncraftable and the progression in Immersive engineering a lot harder.
 
**Steps to reproduce:**
1.
2.
3.

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**

**Forge Version:**

**Server Version:**

**Modpack Version:** 13.2.4

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**
No
 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

**Gist:** https://gist.github.com/

**Pastebin:** https://pastebin.com/

**Hastebin:** https://hastebin.com/

**Comment by BedrockLegends** [comment]
Should have been fixed in earlyier versions

**Comment by SzerencsesDenes** [comment]
I just created a new single player world on v13.2.4 and it's still there. The only difference is that i see a new vilalger trade in JEI for the circuit board, but that does not solves the problem entirely. Btw how come i don't see that trade option on my server it should be updated as well.
