### ISSUE TITLE
Gobber ore not appearing

### ISSUE THREAD

**Issue by davidogame** [BedrockLegends/Monumental-Experience#117]
**Please do not posted issues that are asking for Server Files**

**Issue description:**
Gobber ore is not appearing on the overworld. 
Even gobber ore is not on jei.

 
**Steps to reproduce:**
1.
2.
3.

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**

**Forge Version:**
36.2.4

**Server Version:**
13.2.1

**Modpack Version:**
13.2.1

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**

 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

**Gist:** https://gist.github.com/

**Pastebin:** https://pastebin.com/

**Hastebin:** https://hastebin.com/

**Comment by BedrockLegends** [comment]
I have seen some appearing
