### ISSUE TITLE
Galacticraft Quest

### ISSUE THREAD

**Issue by BrandinoMandino** [BedrockLegends/Monumental-Experience#12]
**Please do not posted issues that are asking for Server Files**

**Issue description:**
The quests for the research papers for Jupiter, Chalos, Pluto, Neptune. I do not know about Ceres and Kepler22b but the others worked fine.
On a side note I play on the server and once this issue is fixed can I get the research paper for Jupiter and Chalos and Neptune cause I learned already without realizing it did not give the progress for the papers and as far as I know you can not get them again once learned.

 
**Steps to reproduce:**
1.
2.
3.

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**
17.7
**Forge Version:**
14.23.5.2854

**Server Version:**

**Modpack Version:**
17.7

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**
no
 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

**Gist:** https://gist.github.com/

**Pastebin:** https://pastebin.com/

**Hastebin:** https://hastebin.com/

**Comment by BedrockLegends** [comment]
@BrandinoMandino Your posted this under the wrong modpack
