### ISSUE TITLE
Vanilla hopper has the same recipe as the Speedy Hopper I

### ISSUE THREAD

**Issue by Sintinium** [BedrockLegends/Monumental-Experience#135]
**Issue description:**
The normal hopper and the Speedy Hopper I has the same recipe

**Modpack Version:**
13.2.11

**Comment by ModernGamingWorld** [comment]
@Sintinium Use Polymorph to change recipes like this https://www.curseforge.com/minecraft/mc-mods/polymorph

**Comment by ModernGamingWorld** [comment]
Updated Recipe uses Tags, So there is no conflict here. Just use another hopper that is not the wooden one
