### ISSUE TITLE
can't download mod pack

### ISSUE THREAD

**Issue by ryanj1792** [BedrockLegends/Monumental-Experience#16]
![image](https://user-images.githubusercontent.com/75564549/101276938-76acc680-37a8-11eb-8418-2f9c0653c961.png)

it just says can't find files after a few seconds of loading

**Comment by Oznerool** [comment]
i have the same problem

**Comment by OgnistyPoland** [comment]
Support said "use GDLauncher it worked for mee" and then banned me for not having premium account, cool not gonna lie
