### ISSUE TITLE
randam issue

### ISSUE THREAD

**Issue by Esteria** [BedrockLegends/Monumental-Experience#161]
- worthless gem ores (like Ruby) from Emendatus Enigmatica spawn too much in underground
- Wooden Backpack requied by quest that not craftable
- when break Rich Soil, it drops nature essence

**Comment by ModernGamingWorld** [comment]
Gem Ores I aware of and did not disable them cause I was not risking Maps
Two Wooden Backpack Quest is already slated to be removed
If Rich Soils be included in drops of Essences then it means a mod messed up their tags
