### ISSUE TITLE
download of modpack still fails

### ISSUE THREAD

**Issue by ryanj1792** [BedrockLegends/Monumental-Experience#18]
not sure why this issue was just deleted? didn't see any response to help

even with the mod pack updated to 5.2 still get the error

![image](https://user-images.githubusercontent.com/75564549/101317257-0f4d5000-3856-11eb-8c51-ebb43cbd04b1.png)

**Comment by BedrockLegends** [comment]
Use GDLauncher, curse is broken - Click Download if u cant find the Download
https://gdevs.io/
