### ISSUE TITLE
alchemist catalyst

### ISSUE THREAD

**Issue by karbure** [BedrockLegends/Monumental-Experience#183]
Hello
I am looking to create an alchemist catalyst but the problem is that you need an infused rock which is necessary to create the catalyst ... unless there is another solution that I have not seen
Thanks in advance
(ps: this is a google translation, I'm french)

**Comment by karbure** [comment]
ah sorry i was talking about the transmutation catalyst
^^' from nature's aura
good year !!! ^^

**Comment by ModernGamingWorld** [comment]
![2022-01-05_01 15 29](https://user-images.githubusercontent.com/75923060/148175852-303666f3-7e91-4128-a1e9-a6b54df95782.png)
