### ISSUE TITLE
Modpack Doesn't Load

### ISSUE THREAD

**Issue by DizzyDJW** [BedrockLegends/Monumental-Experience#185]
**Please do not posted issues that are asking for Server Files**

**Issue description:**
It remains stuck on Splashscreen then goes to black screen.
 

 
**Steps to reproduce:**
1. Launch Game
2. See Issue
3.

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**

**Forge Version:**
36.2.22

**Server Version:**

**Modpack Version:**
15.0.12

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**
No
 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 
![image](https://user-images.githubusercontent.com/26727521/148640402-3c21c5cd-ced0-4358-9a50-54a8c5a7703c.png)

**Comment by ModernGamingWorld** [comment]
It does load, it just takes time to load
