### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by mogcid** [BedrockLegends/Monumental-Experience#187]
**Please do not posted issues that are asking for Server Files**

**Issue description:**
[crash-2022-01-31_15.16.53-client.txt](https://github.com/BedrockLegends/Monumental-Experience/files/7971414/crash-2022-01-31_15.16.53-client.txt)

 
**Steps to reproduce:**
1.
2.
3.

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**

**Forge Version:**
36.2.23

**Server Version:**
16.0.1

**Modpack Version:**
16.0.1

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.*No*

 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

**Gist:** https://gist.github.com/

**Pastebin:** https://pastebin.com/

**Hastebin:** https://hastebin.com/

**Comment by mogcid** [comment]
Close? what?

**Comment by ModernGamingWorld** [comment]
its already fixed in the new version
