### ISSUE TITLE
Game crashes at begining

### ISSUE THREAD

**Issue by Feky** [BedrockLegends/Monumental-Experience#19]
Download pack from gdlauncher and when I launch it after some time it crashes. This was a fresh install not an update. I deleted everything and downloaded the pack again and it still crashes.

[latest.log](https://github.com/BedrockLegends/Monumental-Experience/files/5677553/latest.log)

**Comment by BedrockLegends** [comment]
@Feky its randompatches doing it, Might be fixed in the next version

**Comment by Feky** [comment]
So what I'm supposed to do now or new people who download the pack, they cant play it?

**Comment by BedrockLegends** [comment]
I am working on that, but been tied up. Will try and fix it soon as we can

**Comment by SkuxxDeluxe** [comment]
Same issue with 5.5, Crashes on startup.
Tried on a fresh install, same deal.

Error log if its helpful.
https://justpaste.it/9i1g6

**Comment by BedrockLegends** [comment]
Will be fixed when I can get a fix out as Randompatches has been updated in the new versions I am just waiting on a few more mods and such
