### ISSUE TITLE
making a server

### ISSUE THREAD

**Issue by BlahLeek** [BedrockLegends/Monumental-Experience#193]
![Error](https://user-images.githubusercontent.com/77375006/152249742-9ad5e707-ad7c-47c6-a5b5-bdce4f9b7555.PNG)
Not sure what, "cannot access class sun.security.util.manifestentryverifier... etc. etc.

**Comment by ModernGamingWorld** [comment]
Monumental 1.18 is under no support and no help, I have told people that I will not accept support for 1.18 and how I know this is 1.18 is I see Java version 17

**Comment by BlahLeek** [comment]
as a matter of fact we have download the 1.16 version but now that you say that i think i see the issue.
we knew that the 1.18 version doesnt work so we downloaded the 1.16 server pack and that is what loads up after clickeing the run.bat file

**Comment by ModernGamingWorld** [comment]
Java 17 only works on 1.18 reason-

**Comment by BlahLeek** [comment]
sorry toi bother  but how do we go about obtaining an older verson of java for a 1.16 server

**Comment by ModernGamingWorld** [comment]
https://adoptium.net/archive.html?variant=openjdk17&jvmVariant=hotspot
