### ISSUE TITLE
Whenever I die items stop dropping

### ISSUE THREAD

**Issue by JOKONOLO** [BedrockLegends/Monumental-Experience#199]
**Please do not posted issues that are asking for Server Files**

**Issue description:**
Whenever I die for the first time in the game, after I changed the gamerule keppInventory to true(not sure if it has something to do with the issue), when I respawn and drop an item on the ground it doesn't drop and disappears from my inventory, it's the same with breaking a block. Reentering the game doesn't fix it, neither does creating another map, but closing the game and reopening it fixes the issue. The game doesn't crash and there are no crashlogs.

**Steps to reproduce:**
1.Change gamerule keepInventory to true (not sure if it changes the outcome)
2.Die and respawn
3.Whenever I drop an item on the ground or break a block, it doesn't drop and it just disappears.

**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**
Monumental Experience-16.0.7.zip

**Forge Version:**
36.2.26

**Server Version:**

**Modpack Version:**
16.0.7

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**
All that I have changed is that I set gamerule keepInventory to true and set the difficulty to hard

**Comment by Wangsca** [comment]
I have the exact issue as listed above, including the game rule change that was noted.  Nothing else has been modified in any way.

**Comment by alexanderheuts** [comment]
Issue confirmed for version 16.0.17.

Running both client and my own server. If one of the players dies blocks and mobs no longer drop/spawn loot. Restarting the server fixes the issue (until someone dies).

No changes to the modpack. Running 16.0.17 client and server as provided. 
Gamerules mobGriefing false and keepInventory true are set.

**Comment by ModernGamingWorld** [comment]
I ignore this issue as there is no way to tell what mod is causing this, I dont have time to go through over 300 mods
