### ISSUE TITLE
Crash with woodcutter

### ISSUE THREAD

**Issue by LokyLive** [BedrockLegends/Monumental-Experience#201]
**Issue description:**

 I was using woodcutter to craft wooden fence and the game crashed

**Server Version:**
.29

**Hastebin:**
https://www.toptal.com/developers/hastebin/corusijedi.rb

**Comment by ModernGamingWorld** [comment]
Well that's from My Mod and we currently are not updating it for 1.16.5 at the moment, we moved to 1.18.2 development and may backport changes down the road
