### ISSUE TITLE
Monumental+Experiencev16.0.30

### ISSUE THREAD

**Issue by JohnDeW737** [BedrockLegends/Monumental-Experience#202]
**Please do not posted issues that are asking for Server Files**

**Issue description:**
When downloading the client modpack and the server pack, if you open the mods folder it shows a mismatch of mods.
 

 
**Steps to reproduce:**
1. '16.0.30 server' mods folder shows 335 items
2. '16.0.30 modpack client' mods folder shows 383 items
3.

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**

**Forge Version:**

**Server Version:**
![unknown](https://user-images.githubusercontent.com/101954790/159142151-0bd308e3-4b2c-4ea9-85dd-5b777d2b316a.png)

**Modpack Version:**
16.0.30

![unknown](https://user-images.githubusercontent.com/101954790/159142154-c4d1fd7c-d21b-4a19-8c69-ee0eced8b130.png)

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**

 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

**Gist:** https://gist.github.com/

**Pastebin:** https://pastebin.com/

**Hastebin:** https://hastebin.com/

**Comment by ModernGamingWorld** [comment]
This is not a bug, Please DO NOT POST THIS AGAIN, The server files are meant to be less Mods as they HAVE MOST TO ALL client Side Mods removed as there should never be CLIENT SIDE mods on the SERVER Side unless needed for something
