### ISSUE TITLE
Nether Gobber Ore not Spawning

### ISSUE THREAD

**Issue by syhros** [BedrockLegends/Monumental-Experience#205]
After exploring 1000s of blocks in the Nether I'm unable to find any Gobber ore in my Monumental Experience Server. It's v16.0.46 and upon loading up a fresh Minecraft install with just Gobber installed the only config difference that made the Nether Gobber not spawn was the size of gobber ore pockets in the config:

#Size of Gobber Nether Ore pockers [0-100, default: 3]
#Range: 0 - 100
gobberOreNetherSize = 3

This is set to 2 in Monumental Experience and upon changing it to 3 the ore starts spawning again, was this an intentional change to stop the ore spawning and to only obtain Nether Gobber through x6 Compressed Netherrack?

**Comment by ModernGamingWorld** [comment]
I mean this is already fixed in the rewrite, so I am closing this
