### ISSUE TITLE
mystical agriculture

### ISSUE THREAD

**Issue by lloryap** [BedrockLegends/Monumental-Experience#209]
**Please do not posted issues that are asking for Server Files**

**Issue description:**
when creating infusion crystals of the next tiers the original isnt used therefor you can create a massive amount of crystals from the next tier as it only uses one use so you can basically crate 256 of the next tier and then incrementally create the next tier. before in he older versions you would use up all the uses to create the newer one. 
 

 
**Steps to reproduce:**
1.craft a infusion crystal
2.
3.

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**
Newest

**Forge Version:**
1.16.5

**Server Version:**

**Modpack Version:**

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**

 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

**Gist:** https://gist.github.com/

**Pastebin:** https://pastebin.com/

**Hastebin:** https://hastebin.com/

**Comment by ModernGamingWorld** [comment]
@lloryap The Basic default Infusion crystal was disabled to force you the Inferium in fused crystal, so idk what u mean by this being an issue

**Comment by ModernGamingWorld** [comment]
and My guess is this is already fixed in the next release since we have rewritten the scripts
