### ISSUE TITLE
No loot from animals or mobs when you do more dmg than their health bar.

### ISSUE THREAD

**Issue by Koutsokou** [BedrockLegends/Monumental-Experience#211]
When you do more dmg than the health mob/animal has, the body and loot just vanish.
Edit: If it has taken dmg then it will not vanish.
 
Forge Version: 36.2.39

Modpack Version: 18.0.3

**Comment by ModernGamingWorld** [comment]
Known Bug and Dupelacated bug from Discord, This issue will be closed as currently there is no way to fix this
