### ISSUE TITLE
can't craft the Compressed Stone from mod Prefab

### ISSUE THREAD

**Issue by caoyi2006200** [BedrockLegends/Monumental-Experience#212]
**Please do not posted issues that are asking for Server Files**

**Issue description:**
can't craft the Compressed Stone from mod Prefab.

 

 
**Steps to reproduce:**
1.I want to craft the Starting House. but i discover that I can't craft the Compressed Stone.
2.
3.

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**
2.0.53
**Forge Version:**
43.1.32

**Server Version:**

**Modpack Version:**

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**

 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

**Gist:** https://gist.github.com/

**Pastebin:** https://pastebin.com/

**Hastebin:** https://hastebin.com/

**Comment by ModernGamingWorld** [comment]
Please Read THE CHANGE Log, Read Number 3 please. It states we are not accepting Bug reports for 1.19.2 as Mods and forge are still being updated/fixed

Notes
1. This is a super early build of Monumental Experience for 1.19.2
2. As with each alpha builds, Expect that Maps most likely will be reset off and on till mods/forge get stable and the pack reaches beta state
3. Do NOT POST BUG REPORTS FOR 1.19.2, AS Mods and forge are still super buggy and things will most likely take weeks to a month for them to get stable/somewhat bug-free
