### ISSUE TITLE
Remove stupid stamina and watter mod

### ISSUE THREAD

**Issue by Feky** [BedrockLegends/Monumental-Experience#24]
It's annoying that after running I get stamina drained and water. If it's possible at least reduce it so it won't degrade too fast but a better option just to remove it completly.

So what is the name of that mod I want it removed for myself?

**Comment by Deathstar175** [comment]
The stamina, Water bar, and hot/cold system come from the survive mod, feel free to remove it from your client side, but you wont be able to join any server with it still enabled.

**Comment by ModernGamingWorld** [comment]
https://github.com/BedrockLegends/Monumental-Experience/commit/a56681752c4a767ba8c315b05fdeb5500571ca64
