### ISSUE TITLE
it feels progression breaking to have any of the crafting tables to come from lootbags.

### ISSUE THREAD

**Issue by bradleydragon** [BedrockLegends/Monumental-Experience#26]
title

**Comment by Deathstar175** [comment]
This is fixed in the next update to 8.4, the wooden shears were never supposed to be recursive in their crafting recipe and have thus been changed to use planks and a stick.

**Comment by Feky** [comment]
Yeah I get a bunch of items that need to craft from loot boxes. They all should be disabled and only to get food, weapon, armor and some misc items from lootboxes.
