### ISSUE TITLE
survive mod is not needed, (easily fixable server side so no rush to change this)

### ISSUE THREAD

**Issue by bradleydragon** [BedrockLegends/Monumental-Experience#30]
until the survive mod adds in the underarmor system, it is completely unusable, sure you can make potions but those are also a hassle if you just want to go mining, and requires getting to the nether, just to make heat resist potions.
also the stamina system makes multimine unusable, you take damage just by mining one vein.

easy fix serverside to just disable this unfinished mod. so no rush or anything. keep up the good work with taking community feedback.

**Comment by ModernGamingWorld** [comment]
Can you please stop posting issues about how this mod is not good or how this mod is not needed,
