### ISSUE TITLE
Missing libraries and mods

### ISSUE THREAD

**Issue by Impureshine** [BedrockLegends/Monumental-Experience#34]
**Please do not posted issues that are asking for Server Files**

**Issue description:**
Just downloaded the modpack and was greeted with and error message saying i was missing a bunch of libraries and mods.
i was able to find and downlod most of the libraries but im still missing the Architectury mod/library and the Thermal mod/library 
 

 
**Steps to reproduce:**
1. Download modpack from CurseForge
2. Run the modpack

and thats it

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**

**Forge Version:** 
36.0.42

**Server Version:**
N/A

**Modpack Version:**
8.6

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**
No
 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 https://pastebin.com/LUTaR9c4

**Comment by ModernGamingWorld** [comment]
Means you pack did not install right
