### ISSUE TITLE
Pack issues ive seen so far

### ISSUE THREAD

**Issue by Aaronycaro25** [BedrockLegends/Monumental-Experience#35]
Osmium seed has a quest in tier 2 and tier 3 should be in tier 3
Platinum seed has a quest in tier 1 and tier 5 should be in tier 5
Sky stone seed has no recipe 
compact machine tunnels are not craftable. have a ? in quest line
Dark utilities mob filter raid shows a recipe but will not craft tried in crafting table and creates crafters
Thermal quest line has quests for phytosoil that are not craftable have ? in quest
Killing witch Quest is in the animal quest line instead of mob quest 
last not sure if rubber seeds are craftable,  tried the rubber i could make but have not seen any of the rubber trees at all

really enjoying the pack so far and wanted to point out these issues for you

**Comment by ModernGamingWorld** [comment]
@Aaronycaro25 Skystone wont have a recipe, Its only used for decoration
And Datepack/recipes are being fully redone so none of this is an issue anymore
