### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by mikeskey** [BedrockLegends/Monumental-Experience#37]
1. No recipe for the usage of crushed platinum.
2. Iron and Gold nuggets can't be turned back into ingots....the gold deposits in the nether give gold nuggets and therefore are useless at this point.
3. Wheat when put into the player inventory immediately turns into rice. This makes it impossible to use wheat to set a filter on anything as you can't actually have a piece of wheat in your inventory.

**Comment by ModernGamingWorld** [comment]
Datepack/recipes are being fully redone so none of this is an issue anymore
