### ISSUE TITLE
Refined storage/Mystical Agriculture

### ISSUE THREAD

**Issue by mikeskey** [BedrockLegends/Monumental-Experience#41]
Latest server release

1. When attempting to autocraft with refined storage and using the Master Infusion Crystal to make the higher tier essences the crystal is used up instead of being infinite uses like when hand crafting. If using the crafter from cyclic however the crystal doesn't get used up.

2. Refined storage exporters are able to be toggled for redstone activation. Instead when clicking the redstone activation button the exporter switches to fluid mode.

3. While holding a Refined Storage 16 k drive in my hand I clicked the Disk Drive as I was attempting to open it and then had intended on inserting the drive and the one in my hand dissapeared. It did NOT get placed in the drive....it simply vanished. This has happened multiple times when trying to open Refined Storage GUI's with items in hand.

**Comment by mikeskey** [comment]
After testing multiple blocks in Refined Storage the only one which works with the redstone toggle button is the controller. None of the others are able to be toggled and all instead switch the fluid state or do nothing.

**Comment by ModernGamingWorld** [comment]
This sounds more like a mod bug then a me bug

**Comment by mikeskey** [comment]
I can assure you it's not a mod issue if you are referring to the redstone toggle. Just before playing this pack I played the newest Direwolf20 pack which was 16.5 and had refined storage in it and I had no issues with using the redstone toggles.

If you were referring to the Infusion Crystal issue I can't speak to that as I haven't ever tried that in a pack before this one.

**Comment by ModernGamingWorld** [comment]
Whatever it is, I cant test it as I am still trying to get the Major 9.0 version out that will reset everyone and everything

**Comment by ModernGamingWorld** [comment]
Plus all configs were reset in the major overhaul, so i am sure that this may not even existed if its a config issue
