### ISSUE TITLE
The recipe for Kiln Bricks from Immersive Engineering is missing

### ISSUE THREAD

**Issue by squ1b3r** [BedrockLegends/Monumental-Experience#48]
**Please do not posted issues that are asking for Server Files**

**Issue description:**

There seems to be no way to craft Kiln Bricks from Immersive Engineering. Kiln Bricks are required to get Coke Bricks which then required to get Blast Bricks. Which in turn makes it impossible to get steel early game. Also, anything that requires Creosote Oil and Treated Wood Planks is unobtainable because of that. 
 
**Steps to reproduce:**
1. In JEI look for Kiln Bricks
2. Click the block to see recipes
3. The only recipe available is to craft Kiln Bricks

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):** 1.16.5

**Forge Version:** 36.1.23

**Server Version:** 

**Modpack Version:** 10.4

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.** No

**Comment by squ1b3r** [comment]
I poked around a bit and the reason the recipe is broken is because of the malformed JSON for Kiln Bricks. In `kubejs\data\immersiveengineering\recipes\crafting\alloybrick.json` there are commas on lines 5, 8, and 11 which should not be there.

**Comment by ModernGamingWorld** [comment]
Already know and already fixed in the massive 10.5 changed update
