### ISSUE TITLE
Cant make steel

### ISSUE THREAD

**Issue by Fastdragon1107** [BedrockLegends/Monumental-Experience#50]
Maybe I am not doing this correctly but from what I can tell it is not possible to craft steel. So to craft the steel you need coal coke but when I try to make the coal coke I get the immersive engineering coal coke which for some reason can not go into the create grindstone. And when I try to make the emendatus dust it automatically turns into the immersive engineering coal coke. I also tried to use the blast furnace method but it is not possible to make kiln bricks. Even when I go into creative mode to get the other type of coal it just switches automatically. Hope y'all can fix this but otherwise this is a really nice modpack.

**Comment by ModernGamingWorld** [comment]
Well The Klin Blocks already a known issue and already fixed in the giant rewrite/redone of everything version in 10.5 that has no release date and I am sure this same issue is already fixed in it aswell
