### ISSUE TITLE
Brass bottleneck

### ISSUE THREAD

**Issue by djcorbett** [BedrockLegends/Monumental-Experience#52]
75% of the modpack is inaccessible due to needing brass.  Please give a time line for 10.5 as it completely unplayable.  Normally I’m promoting this modpack on Reddit but can’t since it’s been broken

**Comment by laserjet25** [comment]
While we do not currently have a timeline for v11, it has been coming along a lot better than expected. We will hopefully be posting an update soon for something more official.

Brass should be created early game with copper and zinc dust. This should be fairly simple to get by using a hammer with copper/zinc chunks and smelting the bronze dust. Is there a particular example you could give about how this is severely limiting you?

**Comment by ModernGamingWorld** [comment]
Should be fixed in v11.0 when we get it out
