### ISSUE TITLE
Create Brass Ingot Quest Not Working

### ISSUE THREAD

**Issue by rzred** [BedrockLegends/Monumental-Experience#57]
**Special Thank
It's thanks to all the developers that I can enjoy playing this modpack!

**Issue description:**
I can't complete the quests that are accomplished by getting the Create Mod's brass ingot.

When I got the brass ingot, it automatically became the "Emendatus Enigmatica" Mod's brass ingot, and I could not get the quest "Create" Mod's brass ingot.

![スクリーンショット 2021-08-10 003152](https://user-images.githubusercontent.com/53808419/128732761-4c001124-359b-4461-8136-52e8bf2d5dd2.png)

**Forge Version:**
forge-36.1.23

**Modpack Version:**
10.4

**Comment by ModernGamingWorld** [comment]
Fixed in the Rewrite of this modpack, No eta on release date

**Comment by rzred** [comment]
Thank you for the correction, ModernGamingWorld.
I am looking forward to it.
