### ISSUE TITLE
Kiln Brick Monumental Experience

### ISSUE THREAD

**Issue by DreamDespair** [BedrockLegends/Monumental-Experience#58]
In monumental experience you need kiln bricks to make coke bricks, but when you click the recipe in JEI it just shows slabs to blocks but not how to make it. i found on the web that you have fixed this in version 10.5 but i can not find that version on curse. i don't want to cheat them in but i am stuck until there is a solution. i have made no changes in the config files.

**Comment by ModernGamingWorld** [comment]
Already know and Already Fixed in the Full Rewrite and Full Restart of This pack in v11.0 whenever it gets out
