### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by Bladewolfhart** [BedrockLegends/Monumental-Experience#6]
Can't download the pack, twitch keeps saying access denied.

**Comment by lectavison** [comment]
Unable to replicate using latest alpha. unfortunately the 1.15.2 version is not supported do to that version of Minecraft being unstable, and certain mods being removed from curse forge.

**Comment by BedrockLegends** [comment]
@Bladewolfhart your most likely using the 1.15 version and We are not updating that version cause of so many breaking changes on forge end and the fact that a mod got removed by a mod dev, however we are working hard and quickly to get the 1.16 version out
