### ISSUE TITLE
Black Iron Recipe

### ISSUE THREAD

**Issue by djcorbett** [BedrockLegends/Monumental-Experience#62]
Seems to be no way to make Black Iron ingots.  Recipe call for black iron nuggets which are made with black iron ingots

**Comment by ModernGamingWorld** [comment]
@djcorbett If your playing on version 10.whatever those version are broken and version 10.whatever is not being supported anymore as we moved to v11.whatever

Cause if you looked at 11.0 and above that the recipe looks like this

![2021-08-24_17 19 40](https://user-images.githubusercontent.com/75923060/130697616-7c797221-3ccd-453d-ba97-2a1d5c5430ed.png)
