### ISSUE TITLE
World simply won't load

### ISSUE THREAD

**Issue by greggdogg** [BedrockLegends/Monumental-Experience#63]
I've never had this much difficulty loading into a world. I've literally tried 15 times with different settings and every single time the world stops loading at a different percentage. Keep in mind this has never happened to me with any other modpack. After literal hours of trying, I've still yet to successfully load into a world. I guess I won't be playing this pack

Version 11.3

**Comment by ModernGamingWorld** [comment]
@greggdogg Everyone Else that has been playing the pack has not had any issues, My guess its related to the Apotheosis bug that we just found out this morning about
