### ISSUE TITLE
Wrong Ore Drop

### ISSUE THREAD

**Issue by laserjet25** [BedrockLegends/Monumental-Experience#67]
**Please do not posted issues that are asking for Server Files**

**Issue description:**
The nylium soul soil variant of nether quartz drops regular nether quarts instead of the chunks.
 

 
**Modpack Version:**

12.4

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**
No

**Comment by laserjet25** [comment]
The full block name is Nether Quartz Ore - Nylium Soul Soil.

**Comment by ModernGamingWorld** [comment]
Fixed in 12.5
