### ISSUE TITLE
Hall of Fame Astral Sorcery Requirements

### ISSUE THREAD

**Issue by laserjet25** [BedrockLegends/Monumental-Experience#68]
**Please do not posted issues that are asking for Server Files**

**Issue description:**
The Astral Sorcery section in the hall of fame has an incorrect requirement.
 
This needs to be set correctly for the completion of the relevant chapter.
 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**

**Modpack Version:**
12.4

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**
No

**Comment by ModernGamingWorld** [comment]
Should be Fixed in 12.5
