### ISSUE TITLE
Roguelike Dungeons Chests

### ISSUE THREAD

**Issue by laserjet25** [BedrockLegends/Monumental-Experience#69]
**Please do not posted issues that are asking for Server Files**

**Issue description:**
Chests generated in the Roguelike dungeons are all empty. 

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**

**Modpack Version:**
12.4

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**
No

**Comment by noobanidus** [comment]
There was an incompatibility with Dungeon Crawl (I assume that's what you're talking about) as of 2.3.0, which I submitted a PR for to fix (https://github.com/xyroc/DungeonCrawl/pull/93) but I don't believe there's been an updated release.

I'm not sure if that's what's causing the issue you're experiencing but my recommendation would be to ask Dungeon Crawl to do a new release.
