### ISSUE TITLE
Plate Recipe Consumes Wrench & Hammers

### ISSUE THREAD

**Issue by laserjet25** [BedrockLegends/Monumental-Experience#70]
**Please do not posted issues that are asking for Server Files**

**Issue description:**
When crafting plates (4 ingots/1 wrench), the wrench is consumed after crafting. This should not be the case.
 
**Modpack Version:**
12.5

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**
No

**Comment by ModernGamingWorld** [comment]
@laserjet25 There is no way to prevent this at this time

**Comment by laserjet25** [comment]
This is being worked on by the KubeJS team here: https://github.com/KubeJS-Mods/KubeJS/issues/55
