### ISSUE TITLE
Emendatis Iron Doesn't Work Astral Sorcery

### ISSUE THREAD

**Issue by laserjet25** [BedrockLegends/Monumental-Experience#73]
**Please do not posted issues that are asking for Server Files**

**Issue description:**
Enigmatica Emendatis iron does not work when trying to obtain starmetal ore.
 
This is working correctly if using vanilla Minecraft ore.

 
**Steps to reproduce:**
1. Link a crystal to the ore
2. Nothing happens

**Modpack Version:**
12.6

**Comment by ModernGamingWorld** [comment]
Fixed
