### ISSUE TITLE
Dimension loading crash with /back

### ISSUE THREAD

**Issue by Hamderber** [BedrockLegends/Monumental-Experience#81]
Issue description:
Using the /back command to change dimensions from the overworld to get to your corpse causes the game to hang during terrain loading, without causing a crash report to be generated.
  
Steps to reproduce:
1. Die in a dimension that isn't the overworld
2. Use the /back command to go to corpse
3. Crash

Modpack Version:
13.1

Log:
Unavailable due to not being generated

**Comment by Elrol** [comment]
Been swamped with college for months. This week I have a few days  break, and I wont stop working on it till its fixed.
Even if that means i fall behind on class work.
This WILL be fixed this weekend
