### ISSUE TITLE
Broken Recipes

### ISSUE THREAD

**Issue by laserjet25** [BedrockLegends/Monumental-Experience#93]
**Please do not posted issues that are asking for Server Files**

**Issue description:**
The recipes in the following are broken
 
[Recipes](https://github.com/BedrockLegends/Monumental-Experience/files/7158005/message.txt)

**Modpack Version:**
12.2.2

**Comment by ModernGamingWorld** [comment]
Can Ignore Wooden Uitils Broken Items & Iron Age Furniture as the Mod owner of Iron Age is looking at fixing them at somepoint
