### ISSUE TITLE
Create mod, Wash ore chunk recipes

### ISSUE THREAD

**Issue by GeneralScott06** [BedrockLegends/Monumental-Experience#98]
**Please do not posted issues that are asking for Server Files**

**Issue description:**
Crushing wheel from Create mod.  The wheel crushes Nickel, Iron, Silver and Tin in to dusts instead of nuggets.  Lead and osmium work fine.  Haven't tested Gold. 
 
not sure if it was intended to be this way.
 
**Steps to reproduce:**
1.Setup Crushing wheel
2.Throw in Emendatus Enigmatica chunk
3.Get dust instead of nugget

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**

**Forge Version:**
1.16.5

**Server Version:**

13.2.1

**Modpack Version:**

13.2.1

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**
No
 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

**Gist:** https://gist.github.com/

**Pastebin:** https://pastebin.com/

**Hastebin:** https://hastebin.com/

**Comment by laserjet25** [comment]
We have changed the recipe to only output the create chunks now.
